<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
    <PackageVersion Include="Nethermind.MclBindings" Version="1.0.5" />
    <PackageVersion Include="TUnit" Version="1.53.0" />
  </ItemGroup>
</Project>