name: Build MCL

on:
  push:
    branches: [test/build]  
  workflow_dispatch:
    inputs:
      ref:
        description: MCL repo ref
        required: true
        default: master
        type: string
      create-pr:
        description: Create a pull request
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

env:
  RETENTION: 7

jobs:
  

  

  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [x64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out mcl repository
        uses: actions/checkout@v5
        with:
          repository: herumi/mcl
          ref: ${{ github.event.inputs.ref }}

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          ./mklib dll -DMCL_USE_XBYAK=0

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.arch }}
          path: .
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error

