name: Build MCL

on:
  push:
    branches: [test/build]

permissions:
  contents: write
  pull-requests: write

env:
  RETENTION: 7

jobs:
 

  build-windows:
    name: Windows build
    strategy:
      matrix:
        arch: [x64]
    runs-on: ${{ matrix.arch == 'arm64' && 'windows-11-arm' || 'windows-latest' }}
    steps:
      - name: Check out mcl repository
        uses: actions/checkout@v5
        with:
          repository: rubo/mcl
          ref: ${{ github.event.inputs.ref }}

      - name: Build
        run: |
          $env:CFLAGS = " -DMCL_DONT_USE_XBYAK=1"
          cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.arch }}
          cmake --build build --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-${{ matrix.arch }}
          path: build/bin/release/mcl.dll
          retention-days: ${{ env.RETENTION }}
          if-no-files-found: error
